# Generated by Django 2.1 on 2019-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnvSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(default=0)),
                ('src_ip', models.CharField(max_length=25)),
                ('dst_ip', models.CharField(max_length=25)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pkts_num', models.IntegerField(blank=True, null=True)),
                ('pkts_size', models.IntegerField(blank=True, null=True)),
                ('session', models.BooleanField(default=1)),
                ('hash', models.CharField(blank=True, max_length=101, null=True, unique=True)),
                ('category1', models.TextField(blank=True)),
                ('application1', models.TextField(blank=True)),
                ('domain1', models.TextField(blank=True)),
                ('activity1', models.TextField(blank=True)),
                ('category2', models.TextField(blank=True)),
                ('application2', models.TextField(blank=True)),
                ('domain2', models.TextField(blank=True)),
                ('activity2', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'DnvSession',
                'managed': True,
            },
        ),
    ]
